### PR TITLE
Custom port capability

### LINKED ISSUE #370: Change Redis pods exposed port
### Expected behaviour

Possibility to change the redis listen port.
I might be missing something ? is it possible to do it ?

### Actual behaviour

At the moment it looks like it is not exposed explicitly and I have to change the redis-server command but this doesn't work because then the probes dont work since they are configured for 6379 and probably the sentinel integration breaks as well.

### Steps to reproduce the behaviour

This is my RedisFailover resource
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
  namespace: datalayer
  labels:
    app: rfr-redis
spec:
  sentinel:
    replicas: 1
    image: {{ .Values.global.account }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/redis:5.0-alpine
    imagePullPolicy: Always
  redis:
    command:
      - "redis-server"
      - "/redis/redis.conf"
      - "--port 7777"
    customConfig:
      - "maxmemory 9gb"
      - "maxmemory-policy allkeys-lru"
    resources:
      limits:
        cpu: "1"
        memory: "10G"
      requests:
        cpu: "1"
        memory: "10G"
    securityContext:
      runAsUser: 1203
      runAsGroup: 1203
      fsGroup: 1203
    image: {{ .Values.global.account }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/redis:5.0-alpine
    imagePullPolicy: Always
    replicas: 1
    exporter:
      enabled: true
      image: {{ .Values.global.account }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/bitnami/redis-exporter:1.9.0
```

### Environment

How are the pieces configured?
* Redis Operator version - v1.0.0
* Kubernetes version - 1.19

### PR DESCRIPTION
**Pull request by samof76**
Fixes #370 .

Changes proposed on the PR:
- Adds custom port feature to the redis

### CODE REVIEW

**Comment by samof76** [comment]
@ese we definitely needs this multi-tenant service installations.

**Review by ese — APPROVED** [review]

File: operator/redisfailover/service/generator.go [hunk 1]
```diff
@@ -160,15 +175,22 @@ func generateRedisConfigMap(rf *redisfailoverv1.RedisFailover, labels map[string
...
 	namespace := rf.Namespace
 	rfName := strings.Replace(strings.ToUpper(rf.Name), "-", "_", -1)
 
 	labels = util.MergeLabels(labels, generateSelectorLabels(redisRoleName, rf.Name))
 	shutdownContent := fmt.Sprintf(`master=$(redis-cli -h ${RFS_%[1]v_SERVICE_HOST} -p ${RFS_%[1]v_SERVICE_PORT_SENTINEL} --csv SENTINEL get-master-addr-by-name mymaster | tr ',' ' ' | tr -d '\"' |cut -d' ' -f1)
-redis-cli SAVE
 if [ "$master" = "$(hostname -i)" ]; then
   redis-cli -h ${RFS_%[1]v_SERVICE_HOST} -p ${RFS_%[1]v_SERVICE_PORT_SENTINEL} SENTINEL failover mymaster
-fi`, rfName)
+  sleep 31
```
Comment (dbackeus) [inline operator/redisfailover/service/generator.go:186]: What was the point of this sleep?

Given that `TerminationGracePeriodSeconds` for the redis pods is 30 I'm interpreting this as if the `SAVE` command coming after the sleep will never execute.

Is this intended?
